# -*- coding: utf-8 -*-
"""Histogram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ha77Yvxz0as8hzqD01iaM6QPcERDOaSy

Histogram
"""

import matplotlib.pyplot as plt
import numpy as np
data=np.random.randn(1000)
plt.hist(data,bins=30,color='blue',edgecolor='black')
plt.title('Histogram')
plt.ylabel('values')
plt.title('Frequency')
plt.show()

"""ScatterPlot"""

import matplotlib.pyplot as plt

x=[5,7,8,7,2,17,2,9,4,11,12,9,6]
y=[99,86,87,88,100,86,103,87,94,78,77,85,86]
plt.scatter(x,y,color='red')
plt.xlabel('X - Axis')
plt.ylabel('Y - Axis')
plt.title('Scatter Plot')
plt.show()

"""Pie Chart"""

sizes=[15,30,45,10]
labels=['A','B','C','D']
colors=['gold','yellowgreen','lightcoral','lightskyblue']
plt.pie(sizes,labels=labels,colors=colors,autopct='%1.1f%%',shadow=True,startangle=140)
plt.axis('equal')
plt.title('Pie Chart')
plt.show()

"""Box Plot"""

import numpy as np
data=[np.random.normal(0,std,100) for std in range(1,4)]
plt.boxplot(data)
plt.xlabel('Data Sets')
plt.ylabel('Values')
plt.title('Simple Box Plot')
plt.show()