# -*- coding: utf-8 -*-
"""LinePlot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iNiRbN_MaYokicqKxrOTKNWierTHELH-

Line Plot
"""

import matplotlib.pyplot as plt
x=[1,2,3,4,5]
y=[2,3,5,7,11]
plt.plot(x,y,marker='o')
plt.title('Line Plot')
plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')
plt.show()

"""Bar Plot -1"""

categories=['A','B','C','D','E']
values=[4,7,1,8,5]
plt.bar(categories,values)
plt.xlabel('categories')
plt.ylabel('values')
plt.title('Simple Bar Plot')
plt.show()

"""Bar Plot - 2"""

categories=['A','B','C','D']
values=[5,7,3,8]
plt.bar(categories,values,color='purple')
plt.xlabel('categories')
plt.ylabel('values')
plt.title('Simple Bar Plot')
plt.show()