# -*- coding: utf-8 -*-
"""program10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Q9LtlhBhAmjk3LvrkG0huHwai5JsGI3
"""

import seaborn as sns
import matplotlib.pyplot as plt
data=sns.load_dataset('tips')
sns.scatterplot(x='total_bill', y='tip', data=data)
plt.title('Scatter Plot of Total Bill vs. Tip')
plt.xlabel('Total Bill')
plt.ylabel('Tip')
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv ('/content/housing.csv')

data.info()
data.describe()
data.head()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv ('/content/housing1.csv')

plt.figure(figsize=(10, 8))
sns.scatterplot(x='median_house_value', y='housing_median_age',
data=data)
plt.title('Scatter Plot for Median House Value vs. Housing Median Age')
plt.xlabel('Median House Value')
plt.ylabel('Housing Median Age')
plt.show()

data = pd.read_csv ('/content/housing1.csv')
plt.figure(figsize=(15, 10))
sns.boxplot(x='housing_median_age', y='median_house_value', data=data)
plt.title('Box Plot for Feature1 by Target')
plt.show()