# -*- coding: utf-8 -*-
"""ScatterMultiple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b4_9o_ZCNN40ab418rbfPUl6GhYNNb9Q

Scatter Multiple
"""

import matplotlib.pyplot as plt
x1=[1,2,3,4,5]
y1=[2,3,4,5,6]

x2=[2,3,4,5,6]
y2=[3,4,5,6,7]

x3=[1,3,4,7,8]
y3=[5,3,8,3,5]

plt.scatter(x1,y1,color='red',label='Dataset 1')
plt.scatter(x2,y2,color='blue',label='Dataset 2')
plt.scatter(x3,y3,color='green',label='Dataset 3')
plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')
plt.title('Multiple Scatter Pots')
plt.legend()
plt.show()

"""Bubble Chart"""

x=[1,2,3,4,5]
y=[10,15,13,8,7]
sizes=[100,200,300,400,500]
plt.scatter(x,y,s=sizes,alpha=0.5,c='blue')
plt.xlabel('X - Axis')
plt.ylabel('Y - Axis')
plt.title('Bubble Chart')
plt.show()

"""Bubble Chart -2"""

x=[1,2,3,4,5]
y=[10,15,13,8,7]
sizes=[100,200,300,400,500]
colors=[20,30,40,50,60]
plt.scatter(x,y,s=sizes,c=colors,alpha=0.5,cmap='viridis')
plt.colorbar(label='Color Scale')
plt.xlabel('X - Axis')
plt.ylabel('Y - Axis')
plt.title('Bubble Chart with Color Dimension')
plt.show()

"""SubPlots"""

import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 10, 100)
y1 = np.sin(x)
y2 = np.cos(x)

fig, axs = plt.subplots(2, 1, figsize=(8, 8))

axs[0].plot(x, y1, 'b')
axs[0].set_title('Sine Function')
axs[0].set_ylabel('sin(x)')

axs[1].plot(x, y2, 'r')
axs[1].set_title('Cosine Function')
axs[1].set_ylabel('cos(x)')
axs[1].set_xlabel('x')
plt.tight_layout()

"""program 7"""

years = [2001, 2002, 2003, 2004, 2005, 2006, 2007]
car_values = [24000, 22500, 19700, 17500, 14500, 10000, 5800]
plt.figure(figsize=(10, 6))
plt.subplot(111)
plt.plot(years, car_values, linestyle='-', color='red', marker='*', markersize=20,
markerfacecolor='green')
plt.title(" \nMCA 2023-2025", loc="right")
plt.title("Value Depreciation", loc="left")
plt.xlabel("Year")
plt.ylabel("Car Value")
plt.show()

"""program 8"""

month = np.array(['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])
AS = np.array([173,153,195,147,120,144,148,109,174,130,172,131])
LS = np.array([189,189,105,112,173,109,151,197,174,145,177,161])
SLS = np.array([185,185,126,134,196,153,112,133,200,145,167,110])
plt.xlabel('Months of Year', fontsize=18)
plt.ylabel('Sales of Segments')
plt.title('Sales Data')
plt.title('MCA 2023-2025', loc='right')
plt.scatter(month,AS, label='Affordable Segment', color='pink')
plt.scatter(month,LS, label='Luxury Segment', color='yellow')
plt.scatter(month,SLS, label='Super Luxury Segment', color='blue')
plt.show()

"""program 9"""

days = ['Mon', 'Tues', 'Wed', 'Thurs', 'Fri']
drinks_sales = [300, 450, 150, 400, 650]
food_sales = [400, 500, 350, 300, 500]
fig, axs = plt.subplots(2, 1, figsize=(8, 8))
axs[0].plot(days, drinks_sales, linestyle='--', color='cyan', marker='H',
markersize=8,markerfacecolor='magenta', markeredgecolor='black')
axs[0].set_xlabel('Days of Week')
axs[0].set_ylabel('Sale of Drinks')
axs[0].set_title('Sales Data1', loc='right')
axs[0].set_title('MCA 2023-2025', loc='left')
axs[0].grid(True, color='blue', linestyle='dotted')
axs[1].plot(days, food_sales, linestyle='-', color='yellow', marker='D', markersize=8,
markerfacecolor='green', markeredgecolor='red')
axs[1].set_xlabel('Days of Week')
axs[1].set_ylabel('Sale of Food')
axs[1].set_title('Sales Data2', loc='center')
axs[1].grid(True, color='blue', linestyle='dotted')
plt.tight_layout()
plt.show()